inherit_from:
  - .rubocop_airbnb.yml

# 文字数上限
LineLength:
  Max: 115

#解析しないファイル
AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'